package model.enums;

public enum ServerResponseType {
    SENDINGROOMS,FILE, FILERECEIVED, ROOMHASBEENCREATED, TIMESCHANGED, USERSCHANGED, ROOMJOINED, ROOMFULL, WRONGPASSWORD, CHATMSG, SCRAMBLERECEIVED, HOSTGRANTED;
}
